language: go

go: '1.11'

env:
  global:
  - DEP_RELEASE_TAG=v0.5.0
  - FILE_TO_DEPLOY="dist/*"

  # GITHUB_TOKEN
  - secure: "bJ8ON8AfGia2beup2CRLW8QF4l+F87FZHBPjM/zkH5SGvE2OU+Z3wIYYDGIhP4q27rJ1FIGnzOgxAmy8dgXelVPex4oiZKQbwX78mjKUfxrB86uffQx6KUI7Cn3ppOovPB5hjsXOjKpkHjTkoKrwKAwlz7TON1EDHwYdeBHHbpBaIR8W02l7YP+Avqc5GoeVqxVM0t9qDRW9K93cJ3CWzGjlNbol/JIyNzORyVISyStN4boGROmFxxEfsHU1+a8SYunCxjJEdkYY16m60zU0F0jKNVP3h2c55t6oUvrCHZnM7pWJui6X+IdeQmTpEZqPR9wAbzQVrvZSYwrhXLsdhZvxjnEFRUmKnzppEl3fxpbguWvybIkK9gKWbcwcJouv+nW2IGDnChnQEVaBvR6eA+gu38s/gTJBCeWoLcvfum7EH06Iq3VusXUjN5cVLUNKO7bW+KgoSWbxjeQ9r8KBKIinxJ9xvXIo5vCQQLkQj0ELVbRfzYuXE+SutmxJkRpA16HMHYe+IZhteQElepnXVlHLNJdMDJM0H/ZRRyDSxW/7jJma8nzqwlDYTHoPqp3OIKIrRdZQFsquVb+l+dsYtBhpOLFVnKC+g/77P1y0U13aN7Vo+6b8lGZWtl7SogchXyyHhhu9LYtqtDkyuLZWrf/r5mTkfT+/gBBOH9/g1nw="
  # REVIEWDOG_GITHUB_API_TOKEN
  - secure: "WiMy/mwJmAZMhUURSBhQJgGj3/aDTl7BwVsEktCl4GlsDPIQqF8RCLiKp+LTykvEzttULIw201ycP0GpK5e5nBYNEkwfMEo3i1IH7C3LLgQzTjXcp7bvk+2YTCODCSqWbzQbvPq4mnkLCRZ+SVZX0ToMbcE6Zv4/f6AF90W6ZjLOq3K1hB4+bOdzTsH+a4mHb36ucUrWLdnWUvsaefd3Jhz9HuRLJc2SdAUg4+gvjlbiZq/9SoSZyoIOqod+8yqGTfrU8x87RXBE7ins+9eJoCY/I7joWX8Wdq1ZP6YGQLPNRu37dZJRrCg8xkYKlI9zFavIHUHgK1msUH6qB4q1gHLz2kGPLF65QqX0STfM22t6kz1OsdSM9DGYCQ/8o9vgp+ZT2RVh/4zVXW6/FsjwuMdfg8o+07isPmEnriHhmFfSHvGGg85pwMCNQmL7WfDo6TShXKFI7WWG1ErMLTgTUsXMs6O12+NCSFASoPJr3+40Kn/r0o6FRv0ePEyBVdQgrDB6mpdgJKs6KgS5LVJBYJ64cciAb4UvGFqvQns6JAtlliYIzNGBu5FSzCAdzZNQQxFwSqZrgxoqMF2+2Eu/g1ND0d6CRvusOKVb+vfPH2Dgr+mV/k0js65iJfeTcHU29Yks5Q+drQAFfEFC1pueDLWbNIxvJKgHvr+scTWMCfM="

cache:
  directories:
  - $GOPATH/pkg/dep
  - $GOPATH/pkg/mod
  - $HOME/.cache/go-build

jobs:
  include:
  - name: lint
    install: make setup
    script: make lint
    if: type = 'pull_request'

  - &test
    install: make setup
    script: make test
    if: type != 'pull_request'

  - <<: *test
    go: master

  - <<: *test
    go: '1.10'

  - &test-e2e
    <<: *test
    name: "E2E test (go 1.11)"
    sudo: required
    services:
    - docker
    script: make test-e2e
    if: type != 'pull_request'

  # - <<: *test-e2e
  #   go: '1.10'
  #   name: "E2E test (go 1.10)"

  - stage: deploy
    install: make setup
    script: make packages -j4
    deploy:
    - provider: releases
      skip_cleanup: true
      api_key: $GITHUB_TOKEN
      file_glob: true
      file: $FILE_TO_DEPLOY
      on:
        tags: true
    if: type != 'pull_request'
