// Code generated by github.com/izumin5210/gex. DO NOT EDIT.

// +build tools

package tools

// tool dependencies
import (
	_ "github.com/golangci/golangci-lint/cmd/golangci-lint"
	_ "github.com/google/wire/cmd/wire"
	_ "github.com/reviewdog/reviewdog/cmd/reviewdog"
)

//go:generate go build -v -o ./bin/golangci-lint github.com/golangci/golangci-lint/cmd/golangci-lint
//go:generate go build -v -o ./bin/wire github.com/google/wire/cmd/wire
//go:generate go build -v -o ./bin/reviewdog github.com/reviewdog/reviewdog/cmd/reviewdog
