// Code generated by github.com/izumin5210/gex. DO NOT EDIT.

// +build tools

package tools

// tool dependencies
import (
	_ "github.com/golangci/golangci-lint/cmd/golangci-lint"
	_ "github.com/google/go-cloud/wire/cmd/wire"
	_ "github.com/reviewdog/reviewdog/cmd/reviewdog"
)
