// Code generated by github.com/izumin5210/grapi. DO NOT EDIT.

package internal

import (
	"context"

	"github.com/grpc-ecosystem/grpc-gateway/runtime"
	"google.golang.org/grpc"

	api_pb "github.com/srvc/ery/api"
)

// RegisterWithServer implements grapiserver.Server.RegisterWithServer.
func (s *appServiceServerImpl) RegisterWithServer(grpcSvr *grpc.Server) {
	api_pb.RegisterAppServiceServer(grpcSvr, s)
}

// RegisterWithHandler implements grapiserver.Server.RegisterWithHandler.
func (s *appServiceServerImpl) RegisterWithHandler(ctx context.Context, mux *runtime.ServeMux, conn *grpc.ClientConn) error {
	return api_pb.RegisterAppServiceHandler(ctx, mux, conn)
}
