// Code generated by protoc-gen-go. DO NOT EDIT.
// source: app.proto

package api_pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type App_Type int32

const (
	App_TYPE_UNSPECIFIED App_Type = 0
	App_TYPE_LOCAL       App_Type = 1
	App_TYPE_DOCKER      App_Type = 2
	App_TYPE_KUBERNETES  App_Type = 3
)

var App_Type_name = map[int32]string{
	0: "TYPE_UNSPECIFIED",
	1: "TYPE_LOCAL",
	2: "TYPE_DOCKER",
	3: "TYPE_KUBERNETES",
}

var App_Type_value = map[string]int32{
	"TYPE_UNSPECIFIED": 0,
	"TYPE_LOCAL":       1,
	"TYPE_DOCKER":      2,
	"TYPE_KUBERNETES":  3,
}

func (x App_Type) String() string {
	return proto.EnumName(App_Type_name, int32(x))
}

func (App_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{0, 0}
}

type App_Port_Network int32

const (
	App_Port_TCP App_Port_Network = 0
	App_Port_UDP App_Port_Network = 1
)

var App_Port_Network_name = map[int32]string{
	0: "TCP",
	1: "UDP",
}

var App_Port_Network_value = map[string]int32{
	"TCP": 0,
	"UDP": 1,
}

func (x App_Port_Network) String() string {
	return proto.EnumName(App_Port_Network_name, int32(x))
}

func (App_Port_Network) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{0, 0, 0}
}

type App struct {
	// Required. Output only.
	AppId string `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	// Required.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Required.
	Hostname string `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	// Required.
	Type App_Type `protobuf:"varint,4,opt,name=type,proto3,enum=srvc.ery.App_Type" json:"type,omitempty"`
	// Required.
	Ports []*App_Port `protobuf:"bytes,5,rep,name=ports,proto3" json:"ports,omitempty"`
	// Required. Output only.
	Ip                   string   `protobuf:"bytes,6,opt,name=ip,proto3" json:"ip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *App) Reset()         { *m = App{} }
func (m *App) String() string { return proto.CompactTextString(m) }
func (*App) ProtoMessage()    {}
func (*App) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{0}
}

func (m *App) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_App.Unmarshal(m, b)
}
func (m *App) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_App.Marshal(b, m, deterministic)
}
func (m *App) XXX_Merge(src proto.Message) {
	xxx_messageInfo_App.Merge(m, src)
}
func (m *App) XXX_Size() int {
	return xxx_messageInfo_App.Size(m)
}
func (m *App) XXX_DiscardUnknown() {
	xxx_messageInfo_App.DiscardUnknown(m)
}

var xxx_messageInfo_App proto.InternalMessageInfo

func (m *App) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *App) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *App) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *App) GetType() App_Type {
	if m != nil {
		return m.Type
	}
	return App_TYPE_UNSPECIFIED
}

func (m *App) GetPorts() []*App_Port {
	if m != nil {
		return m.Ports
	}
	return nil
}

func (m *App) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

type App_Port struct {
	// Required.
	Network App_Port_Network `protobuf:"varint,1,opt,name=network,proto3,enum=srvc.ery.App_Port_Network" json:"network,omitempty"`
	// Required.
	ExposedPort uint32 `protobuf:"varint,2,opt,name=exposed_port,json=exposedPort,proto3" json:"exposed_port,omitempty"`
	// Required. Output only.
	InternalPort uint32 `protobuf:"varint,3,opt,name=internal_port,json=internalPort,proto3" json:"internal_port,omitempty"`
	// Optional.
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *App_Port) Reset()         { *m = App_Port{} }
func (m *App_Port) String() string { return proto.CompactTextString(m) }
func (*App_Port) ProtoMessage()    {}
func (*App_Port) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{0, 0}
}

func (m *App_Port) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_App_Port.Unmarshal(m, b)
}
func (m *App_Port) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_App_Port.Marshal(b, m, deterministic)
}
func (m *App_Port) XXX_Merge(src proto.Message) {
	xxx_messageInfo_App_Port.Merge(m, src)
}
func (m *App_Port) XXX_Size() int {
	return xxx_messageInfo_App_Port.Size(m)
}
func (m *App_Port) XXX_DiscardUnknown() {
	xxx_messageInfo_App_Port.DiscardUnknown(m)
}

var xxx_messageInfo_App_Port proto.InternalMessageInfo

func (m *App_Port) GetNetwork() App_Port_Network {
	if m != nil {
		return m.Network
	}
	return App_Port_TCP
}

func (m *App_Port) GetExposedPort() uint32 {
	if m != nil {
		return m.ExposedPort
	}
	return 0
}

func (m *App_Port) GetInternalPort() uint32 {
	if m != nil {
		return m.InternalPort
	}
	return 0
}

func (m *App_Port) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ListAppsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListAppsRequest) Reset()         { *m = ListAppsRequest{} }
func (m *ListAppsRequest) String() string { return proto.CompactTextString(m) }
func (*ListAppsRequest) ProtoMessage()    {}
func (*ListAppsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{1}
}

func (m *ListAppsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListAppsRequest.Unmarshal(m, b)
}
func (m *ListAppsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListAppsRequest.Marshal(b, m, deterministic)
}
func (m *ListAppsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListAppsRequest.Merge(m, src)
}
func (m *ListAppsRequest) XXX_Size() int {
	return xxx_messageInfo_ListAppsRequest.Size(m)
}
func (m *ListAppsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListAppsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListAppsRequest proto.InternalMessageInfo

type ListAppsResponse struct {
	Apps                 []*App   `protobuf:"bytes,1,rep,name=apps,proto3" json:"apps,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListAppsResponse) Reset()         { *m = ListAppsResponse{} }
func (m *ListAppsResponse) String() string { return proto.CompactTextString(m) }
func (*ListAppsResponse) ProtoMessage()    {}
func (*ListAppsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{2}
}

func (m *ListAppsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListAppsResponse.Unmarshal(m, b)
}
func (m *ListAppsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListAppsResponse.Marshal(b, m, deterministic)
}
func (m *ListAppsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListAppsResponse.Merge(m, src)
}
func (m *ListAppsResponse) XXX_Size() int {
	return xxx_messageInfo_ListAppsResponse.Size(m)
}
func (m *ListAppsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListAppsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListAppsResponse proto.InternalMessageInfo

func (m *ListAppsResponse) GetApps() []*App {
	if m != nil {
		return m.Apps
	}
	return nil
}

type GetAppRequest struct {
	AppId                string   `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAppRequest) Reset()         { *m = GetAppRequest{} }
func (m *GetAppRequest) String() string { return proto.CompactTextString(m) }
func (*GetAppRequest) ProtoMessage()    {}
func (*GetAppRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{3}
}

func (m *GetAppRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAppRequest.Unmarshal(m, b)
}
func (m *GetAppRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAppRequest.Marshal(b, m, deterministic)
}
func (m *GetAppRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAppRequest.Merge(m, src)
}
func (m *GetAppRequest) XXX_Size() int {
	return xxx_messageInfo_GetAppRequest.Size(m)
}
func (m *GetAppRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAppRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAppRequest proto.InternalMessageInfo

func (m *GetAppRequest) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

type CreateAppRequest struct {
	App                  *App     `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAppRequest) Reset()         { *m = CreateAppRequest{} }
func (m *CreateAppRequest) String() string { return proto.CompactTextString(m) }
func (*CreateAppRequest) ProtoMessage()    {}
func (*CreateAppRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{4}
}

func (m *CreateAppRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAppRequest.Unmarshal(m, b)
}
func (m *CreateAppRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAppRequest.Marshal(b, m, deterministic)
}
func (m *CreateAppRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAppRequest.Merge(m, src)
}
func (m *CreateAppRequest) XXX_Size() int {
	return xxx_messageInfo_CreateAppRequest.Size(m)
}
func (m *CreateAppRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAppRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAppRequest proto.InternalMessageInfo

func (m *CreateAppRequest) GetApp() *App {
	if m != nil {
		return m.App
	}
	return nil
}

type UpdateAppRequest struct {
	App                  *App     `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateAppRequest) Reset()         { *m = UpdateAppRequest{} }
func (m *UpdateAppRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateAppRequest) ProtoMessage()    {}
func (*UpdateAppRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{5}
}

func (m *UpdateAppRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateAppRequest.Unmarshal(m, b)
}
func (m *UpdateAppRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateAppRequest.Marshal(b, m, deterministic)
}
func (m *UpdateAppRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateAppRequest.Merge(m, src)
}
func (m *UpdateAppRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateAppRequest.Size(m)
}
func (m *UpdateAppRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateAppRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateAppRequest proto.InternalMessageInfo

func (m *UpdateAppRequest) GetApp() *App {
	if m != nil {
		return m.App
	}
	return nil
}

type DeleteAppRequest struct {
	AppId                string   `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteAppRequest) Reset()         { *m = DeleteAppRequest{} }
func (m *DeleteAppRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteAppRequest) ProtoMessage()    {}
func (*DeleteAppRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{6}
}

func (m *DeleteAppRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAppRequest.Unmarshal(m, b)
}
func (m *DeleteAppRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAppRequest.Marshal(b, m, deterministic)
}
func (m *DeleteAppRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAppRequest.Merge(m, src)
}
func (m *DeleteAppRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteAppRequest.Size(m)
}
func (m *DeleteAppRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAppRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAppRequest proto.InternalMessageInfo

func (m *DeleteAppRequest) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func init() {
	proto.RegisterEnum("srvc.ery.App_Type", App_Type_name, App_Type_value)
	proto.RegisterEnum("srvc.ery.App_Port_Network", App_Port_Network_name, App_Port_Network_value)
	proto.RegisterType((*App)(nil), "srvc.ery.App")
	proto.RegisterType((*App_Port)(nil), "srvc.ery.App.Port")
	proto.RegisterType((*ListAppsRequest)(nil), "srvc.ery.ListAppsRequest")
	proto.RegisterType((*ListAppsResponse)(nil), "srvc.ery.ListAppsResponse")
	proto.RegisterType((*GetAppRequest)(nil), "srvc.ery.GetAppRequest")
	proto.RegisterType((*CreateAppRequest)(nil), "srvc.ery.CreateAppRequest")
	proto.RegisterType((*UpdateAppRequest)(nil), "srvc.ery.UpdateAppRequest")
	proto.RegisterType((*DeleteAppRequest)(nil), "srvc.ery.DeleteAppRequest")
}

func init() { proto.RegisterFile("app.proto", fileDescriptor_e0f9056a14b86d47) }

var fileDescriptor_e0f9056a14b86d47 = []byte{
	// 636 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x94, 0xcf, 0x6e, 0xd3, 0x40,
	0x10, 0xc6, 0xeb, 0xd8, 0x49, 0x9a, 0x69, 0x93, 0x9a, 0x01, 0x4a, 0xea, 0x22, 0x9a, 0x1a, 0xa9,
	0x0a, 0x1c, 0x6c, 0x29, 0x85, 0x0b, 0x9c, 0xd2, 0xc4, 0x40, 0x69, 0xd5, 0x46, 0x6e, 0x22, 0x04,
	0x97, 0xc8, 0x69, 0x96, 0xd6, 0xa2, 0xf5, 0x0e, 0xf6, 0xa6, 0x10, 0x21, 0x2e, 0xbc, 0x02, 0xef,
	0xc0, 0x1b, 0x70, 0xe1, 0x35, 0x78, 0x05, 0x1e, 0x04, 0x79, 0x1d, 0xe7, 0x8f, 0x5b, 0x0e, 0xdc,
	0xbc, 0x33, 0xdf, 0xfc, 0xf6, 0x9b, 0x2f, 0xd1, 0x42, 0xc9, 0x23, 0xb2, 0x28, 0xe4, 0x82, 0xe3,
	0x72, 0x14, 0x5e, 0x9d, 0x5a, 0x2c, 0x1c, 0x1b, 0xf7, 0xcf, 0x38, 0x3f, 0xbb, 0x60, 0xb6, 0x47,
	0xbe, 0xed, 0x05, 0x01, 0x17, 0x9e, 0xf0, 0x79, 0x10, 0x25, 0x3a, 0x63, 0x73, 0xd2, 0x95, 0xa7,
	0xc1, 0xe8, 0xbd, 0xcd, 0x2e, 0x49, 0x8c, 0x93, 0xa6, 0xf9, 0x4b, 0x05, 0xb5, 0x49, 0x84, 0x77,
	0xa1, 0xe0, 0x11, 0xf5, 0xfd, 0x61, 0x55, 0xa9, 0x29, 0xf5, 0x92, 0x9b, 0xf7, 0x88, 0xf6, 0x87,
	0x88, 0xa0, 0x05, 0xde, 0x25, 0xab, 0xe6, 0x64, 0x51, 0x7e, 0xa3, 0x01, 0xcb, 0xe7, 0x3c, 0x12,
	0xb2, 0xae, 0xca, 0xfa, 0xf4, 0x8c, 0x3b, 0xa0, 0x89, 0x31, 0xb1, 0xaa, 0x56, 0x53, 0xea, 0x95,
	0x06, 0x5a, 0xa9, 0x45, 0xab, 0x49, 0x64, 0x75, 0xc7, 0xc4, 0x5c, 0xd9, 0xc7, 0x3a, 0xe4, 0x89,
	0x87, 0x22, 0xaa, 0xe6, 0x6b, 0x6a, 0x7d, 0x25, 0x2b, 0xec, 0xf0, 0x50, 0xb8, 0x89, 0x00, 0x2b,
	0x90, 0xf3, 0xa9, 0x5a, 0x90, 0xf7, 0xe4, 0x7c, 0x32, 0x7e, 0x2a, 0xa0, 0xc5, 0x7d, 0x7c, 0x02,
	0xc5, 0x80, 0x89, 0x4f, 0x3c, 0xfc, 0x20, 0x2d, 0x57, 0x1a, 0xc6, 0x75, 0x88, 0x75, 0x94, 0x28,
	0xdc, 0x54, 0x8a, 0xdb, 0xb0, 0xca, 0x3e, 0x13, 0x8f, 0xd8, 0xb0, 0x1f, 0xf3, 0xe5, 0x62, 0x65,
	0x77, 0x65, 0x52, 0x93, 0xe0, 0x87, 0x50, 0xf6, 0x03, 0xc1, 0xc2, 0xc0, 0xbb, 0x48, 0x34, 0xaa,
	0xd4, 0xac, 0xa6, 0x45, 0x29, 0x4a, 0x83, 0xd1, 0x66, 0xc1, 0x98, 0x9b, 0x50, 0x9c, 0xdc, 0x87,
	0x45, 0x50, 0xbb, 0xad, 0x8e, 0xbe, 0x14, 0x7f, 0xf4, 0xda, 0x1d, 0x5d, 0x31, 0x5d, 0xd0, 0xe2,
	0xfd, 0xf1, 0x0e, 0xe8, 0xdd, 0xb7, 0x1d, 0xa7, 0xdf, 0x3b, 0x3a, 0xe9, 0x38, 0xad, 0xfd, 0x17,
	0xfb, 0x4e, 0x5b, 0x5f, 0xc2, 0x0a, 0x80, 0xac, 0x1e, 0x1e, 0xb7, 0x9a, 0x87, 0xba, 0x82, 0x6b,
	0xb0, 0x22, 0xcf, 0xed, 0xe3, 0xd6, 0x81, 0xe3, 0xea, 0x39, 0xbc, 0x0d, 0x6b, 0xb2, 0x70, 0xd0,
	0xdb, 0x73, 0xdc, 0x23, 0xa7, 0xeb, 0x9c, 0xe8, 0xaa, 0x79, 0x0b, 0xd6, 0x0e, 0xfd, 0x48, 0x34,
	0x89, 0x22, 0x97, 0x7d, 0x1c, 0xb1, 0x48, 0x98, 0x4f, 0x41, 0x9f, 0x95, 0x22, 0xe2, 0x41, 0xc4,
	0x70, 0x1b, 0x34, 0x8f, 0x28, 0xaa, 0x2a, 0x32, 0xeb, 0xf2, 0x42, 0x4c, 0xae, 0x6c, 0x99, 0x3b,
	0x50, 0x7e, 0xc9, 0xe2, 0xa9, 0x09, 0xe7, 0x1f, 0xff, 0x07, 0x73, 0x17, 0xf4, 0x56, 0xc8, 0x3c,
	0xc1, 0xe6, 0xa4, 0x5b, 0xa0, 0x7a, 0x44, 0x52, 0x77, 0x8d, 0x1e, 0x77, 0xe2, 0xa1, 0x1e, 0x0d,
	0xff, 0x73, 0xe8, 0x11, 0xe8, 0x6d, 0x76, 0xc1, 0x16, 0x86, 0x6e, 0x36, 0xd5, 0xf8, 0xa1, 0x02,
	0x34, 0x89, 0x4e, 0x58, 0x78, 0xe5, 0x9f, 0x32, 0xec, 0xc0, 0x72, 0x1a, 0x01, 0x6e, 0xcc, 0xc8,
	0x99, 0xa4, 0x0c, 0xe3, 0xa6, 0x56, 0x92, 0x98, 0x59, 0xfe, 0xf6, 0xfb, 0xcf, 0xf7, 0x5c, 0x11,
	0xf3, 0x76, 0x9c, 0x0e, 0xbe, 0x82, 0x42, 0x92, 0x0e, 0xde, 0x9b, 0x0d, 0x2d, 0xe4, 0x65, 0x2c,
	0xae, 0x60, 0xae, 0x4b, 0x80, 0x8e, 0x15, 0x09, 0xb0, 0xbf, 0x24, 0xb6, 0xbf, 0xe2, 0x6b, 0x28,
	0x4d, 0xf3, 0xc3, 0x39, 0x07, 0xd9, 0x50, 0xb3, 0x3c, 0x94, 0xbc, 0x55, 0x33, 0x31, 0xf4, 0x2c,
	0x4e, 0x08, 0xdf, 0x40, 0x69, 0x1a, 0xeb, 0x3c, 0x2b, 0x9b, 0x75, 0x96, 0xb5, 0x25, 0x59, 0x1b,
	0x0d, 0x9c, 0x79, 0xb3, 0x26, 0xfe, 0xa6, 0xe0, 0x69, 0xf4, 0xf3, 0xe0, 0xec, 0xef, 0x61, 0xac,
	0x5b, 0xc9, 0xd3, 0x62, 0xa5, 0x4f, 0x8b, 0xe5, 0xc4, 0x4f, 0x4b, 0xba, 0xfd, 0xe3, 0xcc, 0xf6,
	0x7b, 0xb5, 0x77, 0x0f, 0xce, 0x7c, 0x71, 0x3e, 0x1a, 0x58, 0xa7, 0xfc, 0xd2, 0x8e, 0xb9, 0x36,
	0x0b, 0xc7, 0xf1, 0xb3, 0xf5, 0xdc, 0x23, 0xbf, 0x4f, 0x83, 0x41, 0x41, 0x92, 0x76, 0xff, 0x06,
	0x00, 0x00, 0xff, 0xff, 0xa7, 0xa1, 0x0b, 0x8d, 0xe7, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AppServiceClient is the client API for AppService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AppServiceClient interface {
	ListApps(ctx context.Context, in *ListAppsRequest, opts ...grpc.CallOption) (*ListAppsResponse, error)
	GetApp(ctx context.Context, in *GetAppRequest, opts ...grpc.CallOption) (*App, error)
	CreateApp(ctx context.Context, in *CreateAppRequest, opts ...grpc.CallOption) (*App, error)
	UpdateApp(ctx context.Context, in *UpdateAppRequest, opts ...grpc.CallOption) (*App, error)
	DeleteApp(ctx context.Context, in *DeleteAppRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type appServiceClient struct {
	cc *grpc.ClientConn
}

func NewAppServiceClient(cc *grpc.ClientConn) AppServiceClient {
	return &appServiceClient{cc}
}

func (c *appServiceClient) ListApps(ctx context.Context, in *ListAppsRequest, opts ...grpc.CallOption) (*ListAppsResponse, error) {
	out := new(ListAppsResponse)
	err := c.cc.Invoke(ctx, "/srvc.ery.AppService/ListApps", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appServiceClient) GetApp(ctx context.Context, in *GetAppRequest, opts ...grpc.CallOption) (*App, error) {
	out := new(App)
	err := c.cc.Invoke(ctx, "/srvc.ery.AppService/GetApp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appServiceClient) CreateApp(ctx context.Context, in *CreateAppRequest, opts ...grpc.CallOption) (*App, error) {
	out := new(App)
	err := c.cc.Invoke(ctx, "/srvc.ery.AppService/CreateApp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appServiceClient) UpdateApp(ctx context.Context, in *UpdateAppRequest, opts ...grpc.CallOption) (*App, error) {
	out := new(App)
	err := c.cc.Invoke(ctx, "/srvc.ery.AppService/UpdateApp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appServiceClient) DeleteApp(ctx context.Context, in *DeleteAppRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/srvc.ery.AppService/DeleteApp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AppServiceServer is the server API for AppService service.
type AppServiceServer interface {
	ListApps(context.Context, *ListAppsRequest) (*ListAppsResponse, error)
	GetApp(context.Context, *GetAppRequest) (*App, error)
	CreateApp(context.Context, *CreateAppRequest) (*App, error)
	UpdateApp(context.Context, *UpdateAppRequest) (*App, error)
	DeleteApp(context.Context, *DeleteAppRequest) (*empty.Empty, error)
}

func RegisterAppServiceServer(s *grpc.Server, srv AppServiceServer) {
	s.RegisterService(&_AppService_serviceDesc, srv)
}

func _AppService_ListApps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAppsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServiceServer).ListApps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/srvc.ery.AppService/ListApps",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServiceServer).ListApps(ctx, req.(*ListAppsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppService_GetApp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAppRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServiceServer).GetApp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/srvc.ery.AppService/GetApp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServiceServer).GetApp(ctx, req.(*GetAppRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppService_CreateApp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAppRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServiceServer).CreateApp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/srvc.ery.AppService/CreateApp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServiceServer).CreateApp(ctx, req.(*CreateAppRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppService_UpdateApp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAppRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServiceServer).UpdateApp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/srvc.ery.AppService/UpdateApp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServiceServer).UpdateApp(ctx, req.(*UpdateAppRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppService_DeleteApp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAppRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServiceServer).DeleteApp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/srvc.ery.AppService/DeleteApp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServiceServer).DeleteApp(ctx, req.(*DeleteAppRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AppService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "srvc.ery.AppService",
	HandlerType: (*AppServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListApps",
			Handler:    _AppService_ListApps_Handler,
		},
		{
			MethodName: "GetApp",
			Handler:    _AppService_GetApp_Handler,
		},
		{
			MethodName: "CreateApp",
			Handler:    _AppService_CreateApp_Handler,
		},
		{
			MethodName: "UpdateApp",
			Handler:    _AppService_UpdateApp_Handler,
		},
		{
			MethodName: "DeleteApp",
			Handler:    _AppService_DeleteApp_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "app.proto",
}
